- name: Find the first unused loop device.
  become: true
  shell: losetup -f 
  register: result

- name: Set up a loop device.
  become: true
  command: "losetup {{ result.stdout }} {{ vyos_raw_img }}"

- name: Set vyos_target_drive.
  set_fact:
    vyos_target_drive: "{{ result.stdout }}"
