- name: Install required packages
  become: yes
  apt:
    update_cache: yes
    name:
      - parted
      - e2fsprogs
      - gnupg
      - qemu-utils
    state: present
- name: Download open-vmdk
  get_url:
    url: https://github.com/vmware/open-vmdk/archive/master.zip
    dest: /tmp/master.zip
- name: Extract master.zip into /var/lib/foo
  unarchive:
    src: /tmp/master.zip
    dest: /tmp
- name: Install open-vmdk
  make:
    chdir: /tmp/open-vmdk-master
    target: install
