# Trim filesystems to minimize resulted image
- name: Trim {{ vyos_install_root }}/boot
  become: true
  command: fstrim {{ vyos_install_root }}/boot

- name: Trim {{ vyos_write_root }}
  become: true
  command: fstrim {{ vyos_write_root }}
