- name: Install required packages
  become: true
  apt:
    update_cache: true
    name:
      - parted
      - e2fsprogs
      - gnupg
      - qemu-utils
      - python-lxml
      - aufs-tools
      - grub2
      - python-requests
      - unzip
      - zlib1g-dev
      - squashfs-tools
    state: present
